# Generated by Django 5.2.6 on 2026-03-20 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('alabanza', '0002_alter_group_name_alter_coordinator_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coordinator',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assistance',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='group',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='server',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='coordinator',
            unique_together={('tenant', 'name', 'surname')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('tenant', 'name', 'surname')},
        ),
    ]
