# Generated by Django 4.2.12 on 2025-08-14 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pequediks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('surname', models.CharField(max_length=128, verbose_name='surname')),
                ('user', models.OneToOneField(blank=True, help_text='Link this coordinator profile to a Django user account to allow login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pequediks_staff', to=settings.AUTH_USER_MODEL, verbose_name='user account')),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('birthday', models.DateField(validators=[pequediks.models.validate_date])),
                ('parent_name', models.CharField(blank=True, max_length=128)),
                ('contact_phone', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('promovido', 'Promovido')], default='activo', max_length=10, verbose_name='Estado')),
            ],
            options={
                'unique_together': {('name', 'surname', 'birthday')},
            },
        ),
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pequediks.coordinator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pequediks.group')),
            ],
            options={
                'unique_together': {('name', 'surname')},
            },
        ),
        migrations.CreateModel(
            name='GroupCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pequediks.coordinator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pequediks.group')),
            ],
            options={
                'verbose_name': 'Asignación Grupo-Coordinador',
                'verbose_name_plural': 'Asignaciones Grupo-Coordinador',
                'unique_together': {('group', 'coordinator')},
            },
        ),
        migrations.CreateModel(
            name='assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attended', models.BooleanField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pequediks.child')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pequediks.coordinator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pequediks.group')),
            ],
            options={
                'unique_together': {('child', 'date')},
            },
        ),
    ]
