# Generated by Django 5.1.7 on 2025-08-06 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pequediks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupcoordinator',
            options={'verbose_name': 'Asignación Grupo-Coordinador', 'verbose_name_plural': 'Asignaciones Grupo-Coordinador'},
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link this coordinator profile to a Django user account to allow login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pequediks_staff', to=settings.AUTH_USER_MODEL, verbose_name='user account'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='child',
            unique_together={('name', 'surname', 'birthday')},
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('name', 'surname')},
        ),
    ]
