# Generated by Django 5.1.7 on 2026-05-31 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_seed_default_tenant'),
        ('cunakids', '0007_alter_groupcoordinator_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='child',
            unique_together={('tenant', 'name', 'surname', 'birthday')},
        ),
    ]
