# Generated by Django 5.2.6 on 2026-03-20 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('encuentros', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingparticipant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='churchdatainfo',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='familyparticipantinfo',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='financemovements',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='server',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='summary',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='code',
            field=models.CharField(help_text='Unique code identifying the meeting.', max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='meetingparticipant',
            unique_together={('tenant', 'meeting', 'participant', 'event_date')},
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('tenant', 'email'), name='encuentros_participant_tenant_email_uniq'),
        ),
    ]
