# Generated by Django 5.1.7 on 2025-08-06 03:35

import django.db.models.deletion
import jpro.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('surname', models.CharField(max_length=128)),
                ('birthday', models.DateField(validators=[jpro.models.validate_date])),
                ('parent_name', models.CharField(blank=True, max_length=128)),
                ('contact_phone', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('promovido', 'Promovido')], default='activo', max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('surname', models.CharField(max_length=128, verbose_name='surname')),
                ('user', models.OneToOneField(blank=True, help_text='Link this coordinator profile to a Django user account to allow login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jpro_staff', to=settings.AUTH_USER_MODEL, verbose_name='user account')),
            ],
        ),
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('surname', models.CharField(max_length=128)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jpro.coordinator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jpro.group')),
            ],
        ),
        migrations.CreateModel(
            name='assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attended', models.BooleanField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jpro.child')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jpro.coordinator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jpro.group')),
            ],
            options={
                'unique_together': {('child', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GroupCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpro.coordinator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpro.group')),
            ],
            options={
                'verbose_name': 'Asignación Grupo-Coordinador (Cuna)',
                'verbose_name_plural': 'Asignaciones Grupo-Coordinador (Cuna)',
                'unique_together': {('group', 'coordinator')},
            },
        ),
    ]
