# Generated by Django 5.2.6 on 2026-03-20 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0007_teacher_user'),
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='course',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='grade',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='student',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='subject',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=128, verbose_name='subject name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together={('tenant', 'enrollment', 'lesson_number')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('tenant', 'subject', 'academic_period', 'day_of_week', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('tenant', 'student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('tenant', 'enrollment', 'lesson_number', 'grade_type')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('tenant', 'name', 'surname')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('tenant', 'email'), name='academia_student_tenant_email_uniq'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('tenant', 'email'), name='academia_teacher_tenant_email_uniq'),
        ),
    ]
