# Generated by Django 5.1.7 on 2026-05-02 15:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_seed_default_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='first name')),
                ('last_name', models.CharField(max_length=128, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16, verbose_name='status')),
                ('tenant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant')),
            ],
            options={
                'verbose_name': 'Disciple',
                'verbose_name_plural': 'Disciples',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DiscipleshipGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('coleader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coleading_groups', to='discipulado.disciple')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leading_groups', to='discipulado.disciple')),
                ('tenant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant')),
            ],
            options={
                'verbose_name': 'Discipleship group',
                'verbose_name_plural': 'Discipleship groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscipleshipGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('LEADER', 'Leader'), ('COLEADER', 'Co-Leader')], default='MEMBER', max_length=16, verbose_name='role')),
                ('joined_on', models.DateField(blank=True, null=True, verbose_name='joined on')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('disciple', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to='discipulado.disciple')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='discipulado.discipleshipgroup')),
                ('tenant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant')),
            ],
            options={
                'verbose_name': 'Discipleship group member',
                'verbose_name_plural': 'Discipleship group members',
                'ordering': ['group', 'disciple'],
            },
        ),
        migrations.CreateModel(
            name='DiscipleshipMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(verbose_name='meeting date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='topic')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='COMPLETED', max_length=16, verbose_name='status')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='discipulado.discipleshipgroup')),
                ('tenant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant')),
            ],
            options={
                'verbose_name': 'Discipleship meeting',
                'verbose_name_plural': 'Discipleship meetings',
                'ordering': ['-meeting_date', 'group__name'],
            },
        ),
        migrations.CreateModel(
            name='HostFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=160, verbose_name='family name')),
                ('contact_name', models.CharField(max_length=160, verbose_name='contact name')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='contact phone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16, verbose_name='status')),
                ('tenant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant')),
            ],
            options={
                'verbose_name': 'Host family',
                'verbose_name_plural': 'Host families',
                'ordering': ['family_name'],
            },
        ),
        migrations.AddField(
            model_name='discipleshipgroup',
            name='host_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='discipulado.hostfamily'),
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('JUSTIFIED', 'Justified')], default='PRESENT', max_length=16, verbose_name='attendance status')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('disciple', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='discipulado.disciple')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='discipulado.discipleshipmeeting')),
                ('tenant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant')),
            ],
            options={
                'verbose_name': 'Meeting attendance',
                'verbose_name_plural': 'Meeting attendances',
                'ordering': ['meeting', 'disciple'],
            },
        ),
        migrations.CreateModel(
            name='MeetingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('category', models.CharField(choices=[('SNACK', 'Snack'), ('MATERIAL', 'Material'), ('LOGISTICS', 'Logistics'), ('OTHER', 'Other')], default='SNACK', max_length=16, verbose_name='category')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('paid_to', models.CharField(blank=True, max_length=160, verbose_name='paid to')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('registered_at', models.DateField(verbose_name='registered at')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='discipulado.discipleshipmeeting')),
                ('tenant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant')),
            ],
            options={
                'verbose_name': 'Meeting expense',
                'verbose_name_plural': 'Meeting expenses',
                'ordering': ['-registered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OfferingIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('MISSIONS', 'Missions'), ('SPECIAL', 'Special')], default='GENERAL', max_length=16, verbose_name='category')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('registered_at', models.DateField(verbose_name='registered at')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='discipulado.discipleshipmeeting')),
                ('received_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings_made', to='discipulado.disciple')),
                ('tenant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant')),
            ],
            options={
                'verbose_name': 'Offering income',
                'verbose_name_plural': 'Offering incomes',
                'ordering': ['-registered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='first name')),
                ('last_name', models.CharField(max_length=128, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16, verbose_name='status')),
                ('tenant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant')),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisors',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SupervisionVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='visit date')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervision_visits', to='discipulado.discipleshipmeeting')),
                ('tenant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='discipulado.supervisor')),
            ],
            options={
                'verbose_name': 'Supervision visit',
                'verbose_name_plural': 'Supervision visits',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.AddField(
            model_name='discipleshipgroup',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='discipulado.supervisor'),
        ),
        migrations.AddConstraint(
            model_name='disciple',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('tenant', 'email'), name='discipulado_disciple_tenant_email_uniq'),
        ),
        migrations.AlterUniqueTogether(
            name='discipleshipgroupmember',
            unique_together={('tenant', 'group', 'disciple')},
        ),
        migrations.AlterUniqueTogether(
            name='discipleshipmeeting',
            unique_together={('tenant', 'group', 'meeting_date')},
        ),
        migrations.AlterUniqueTogether(
            name='hostfamily',
            unique_together={('tenant', 'family_name')},
        ),
        migrations.AlterUniqueTogether(
            name='meetingattendance',
            unique_together={('tenant', 'meeting', 'disciple')},
        ),
        migrations.AddConstraint(
            model_name='supervisor',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('tenant', 'email'), name='discipulado_supervisor_tenant_email_uniq'),
        ),
        migrations.AlterUniqueTogether(
            name='supervisionvisit',
            unique_together={('tenant', 'supervisor', 'meeting', 'visit_date')},
        ),
        migrations.AlterUniqueTogether(
            name='discipleshipgroup',
            unique_together={('tenant', 'name')},
        ),
    ]
