# Generated by Django 5.1.7 on 2025-08-06 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusukids', '0011_groupcoordinator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link this coordinator profile to a Django user account to allow login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pusukids_staff', to=settings.AUTH_USER_MODEL, verbose_name='user account'),
        ),
    ]
