# Generated by Django 5.2.6 on 2026-03-20 00:12

import django.db.models.deletion
import pusukids.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('pusukids', '0012_coordinator_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupcoordinator',
            options={'verbose_name': 'AsignaciÃ³n Grupo-Coordinador', 'verbose_name_plural': 'Asignaciones Grupo-Coordinador'},
        ),
        migrations.AlterUniqueTogether(
            name='assistance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='child',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='groupcoordinator',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assistance',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='child',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='fecha',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='group',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='groupage',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='groupcoordinator',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='server',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='weekinfo',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='account.tenant'),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='date',
            field=models.DateField(validators=[pusukids.models.validate_date]),
        ),
        migrations.AlterUniqueTogether(
            name='assistance',
            unique_together={('tenant', 'child', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='child',
            unique_together={('tenant', 'name', 'surname')},
        ),
        migrations.AlterUniqueTogether(
            name='fecha',
            unique_together={('tenant', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='groupage',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='groupcoordinator',
            unique_together={('tenant', 'group', 'coordinator')},
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('tenant', 'name', 'surname')},
        ),
    ]
