# Generated by Django 5.1.7 on 2026-05-23 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusukids', '0014_alter_group_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupcoordinator',
            options={'verbose_name': 'Asignación Grupo-Coordinador', 'verbose_name_plural': 'Asignaciones Grupo-Coordinador'},
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link this coordinator profile to a Django user account to enable login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pusukids_staff', to=settings.AUTH_USER_MODEL, verbose_name='user account'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='groupage',
            name='description',
            field=models.TextField(),
        ),
    ]
